name: tf-torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.1=py37_0
  - astor=0.7.1=py37_0
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.11.27=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - cloudpickle=1.0.0=py_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.3.1=cuda10.0_0
  - cupti=10.0.130=0
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py37h14c3975_1001
  - dask-core=1.2.2=py_0
  - decorator=4.4.0=py_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.0=he983fc9_0
  - gast=0.2.2=py37_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.13=h23475e2_0
  - grpcio=1.16.1=py37hf8bcb03_1
  - h5py=2.8.0=py37h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=hf484d3e_1000
  - imageio=2.5.0=py37_0
  - intel-openmp=2019.3=199
  - ipykernel=5.1.1=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jasper=2.0.14=h07fcdf6_1
  - jinja2=2.10.1=py37_0
  - jpeg=9c=h14c3975_1001
  - jupyter_client=5.2.4=py37_0
  - jupyter_core=4.5.0=py_0
  - keras-applications=1.0.7=py_0
  - keras-preprocessing=1.0.9=py_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.7.1=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h648cc4a_1001
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1=py37_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib-base=3.1.0=py37hfd891ef_1
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2019.3=199
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - mock=2.0.0=py37_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.3=py_0
  - ninja=1.9.0=py37hfd86e86_0
  - notebook=5.6.0=py37_0
  - numpy=1.16.3=py37h7e9f1db_0
  - numpy-base=1.16.3=py37hde5b4d6_0
  - olefile=0.46=py_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1d=h7b6447c_3
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pbr=5.1.3=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pillow=6.0.0=py37he7afcd5_0
  - pip=19.1.1=py37_0
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py37_0
  - protobuf=3.7.1=py37he6710b0_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycparser=2.19=py37_0
  - pyparsing=2.4.0=py_0
  - python=3.7.3=h0371630_0
  - python-dateutil=2.8.0=py_0
  - pytorch=1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0
  - pywavelets=1.0.3=py37hd352d35_1
  - readline=7.0=h7b6447c_5
  - scikit-image=0.15.0=py37he1b5a44_0
  - scipy=1.2.1=py37h7c811a0_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - tensorboard=1.13.1=py37hf484d3e_0
  - tensorflow=1.13.1=gpu_py37hc158e3b_0
  - tensorflow-base=1.13.1=gpu_py37h8d69cac_0
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.9=h84994c4_1001
  - toolz=0.9.0=py_1
  - torchvision=0.4.0=py37_cu100
  - tornado=5.1.1=py37h7b6447c_0
  - traitlets=4.3.2=py37_0
  - werkzeug=0.15.2=py_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - alabaster==0.7.12
    - allennlp==0.8.5
    - atomicwrites==1.3.0
    - babel==2.7.0
    - bleach==3.1.0
    - blessings==1.7
    - blis==0.2.4
    - boto3==1.9.204
    - botocore==1.12.204
    - chardet==3.0.4
    - click==7.0
    - colorama==0.4.1
    - conllu==1.3.1
    - cymem==2.0.2
    - defusedxml==0.6.0
    - django==2.2.1
    - django-tastypie==0.14.2
    - docutils==0.14
    - editdistance==0.5.3
    - entrypoints==0.3
    - falcon==2.0.0
    - fastbpe==0.1.0
    - flaky==3.6.1
    - flask==1.1.1
    - flask-cors==3.0.8
    - ftfy==5.6
    - funcsigs==1.0.2
    - gevent==1.4.0
    - gitresultsmanager==0.4.1
    - gpustat==0.5.0
    - greenlet==0.4.15
    - gunicorn==20.0.4
    - idna==2.8
    - imagesize==1.1.0
    - importlib-metadata==0.19
    - ipython==7.5.0
    - ipython-genutils==0.2.0
    - itsdangerous==1.1.0
    - jedi==0.13.3
    - jmespath==0.9.4
    - joblib==0.13.2
    - jobrun==0.1
    - jsonnet==0.13.0
    - jsonpickle==1.2
    - jsonschema==3.0.1
    - jupyter-client==5.3.1
    - more-itertools==7.2.0
    - murmurhash==1.0.2
    - nltk==3.4.5
    - numpydoc==0.9.1
    - nvidia-ml-py3==7.352.0
    - orderedset==2.0.1
    - overrides==1.9
    - packaging==19.1
    - parsimonious==0.8.1
    - parso==0.4.0
    - pathlib==1.0.1
    - pickleshare==0.7.5
    - plac==0.9.6
    - pluggy==0.12.0
    - preshed==2.0.1
    - psutil==5.6.2
    - ptyprocess==0.6.0
    - py==1.8.0
    - pygments==2.4.0
    - pyrsistent==0.15.3
    - pytest==5.1.1
    - python-mimeparse==1.6.0
    - pytorch-pretrained-bert==0.6.2
    - pytz==2019.1
    - pyyaml==5.1.2
    - pyzmq==18.0.2
    - regex==2019.6.8
    - requests==2.22.0
    - responses==0.10.6
    - s3transfer==0.2.1
    - sacremoses==0.0.35
    - scikit-learn==0.21.3
    - send2trash==1.5.0
    - sentencepiece==0.1.83
    - snowballstemmer==1.9.0
    - spacy==2.1.8
    - sphinx==2.2.0
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - sqlparse==0.3.0
    - srsly==0.1.0
    - tensorboardx==1.8
    - tensorflow-probability==0.6.0
    - terminado==0.8.2
    - texar==0.2.3
    - thinc==7.0.8
    - torchtext==0.4.0
    - tqdm==4.33.0
    - unidecode==1.1.1
    - urllib3==1.25.2
    - wasabi==0.2.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - word2number==1.1
    - zipp==0.6.0
prefix: /mnt/share/rosanne/anaconda3/envs/tf-torch

